model: iTracker
dataset: /path/to/Static-MobilePoG
seed: 6666
calibrate:
  params:
    batch_size: 16
    num_workers: 16
    epoch: 15
    lr: 0.00001
  load:  /path/to/Static-MobilePoG/model_weight
  save: 
    save_path: result/calibrate/ff_itracker_StaticMobilePoG
    save_epoch: 1
  sample_point_num: 1
  pose_num: 1

   